require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test" << "lib"
  t.pattern = "test/**/*_test.rb"
  t.warning = false
end

begin
  require "standard/rake"
  task default: %i[test standard]
rescue LoadError
  task default: :test
end

namespace :mcp do
  desc "Rebuild registry.json from ../gem"
  task :build do
    sh "exe/ruby-ui-mcp-build"
  end
end
