name: "ruby_ui"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../../ruby_ui:/workspaces/ruby_ui:cached
      - ../../web:/workspaces/web:cached
    ports:
      - "3000:3000"
      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
